# Generated by Django 3.2.4 on 2021-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='location_id',
            new_name='location',
        ),
    ]
